$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: llama31-70b-instruct-aml-1
endpoint_name: llama3-8b-nim-endpoint-aml-1
# Model is not used.
model: azureml://registries/azureml-meta/models/Meta-Llama-3-8B-Instruct/versions/5
model_mount_path: /triton-models
environment:
  name: llama31_70b_instruct_patch_env
  image: nimdemocr.azurecr.io/nim/meta/llama-3.1-70b-instruct:latest
  inference_config:
      liveness_route:
          path: /v1/health/ready
          port: 8000
      readiness_route:
          path: /v1/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: Standard_NC48ads_A100_v4
instance_count: 1
request_settings:
  max_concurrent_requests_per_instance: 30
  request_timeout_ms: 10000
environment_variables:
    NGC_API_KEY:  ${{azureml://connections/ngc/credentials/NGC_API_KEY}}
